# Exported from Render on 2026-01-05T14:21:03Z
version: "1"
services:
- type: web
  name: general-notification
  runtime: node
  repo: https://github.com/bad-boy-01/general-notification
  plan: free
  envVars:
  - key: DISCORD_WEBHOOK
    sync: false
  - key: PUPPETEER_EXECUTABLE_PATH
    value: /usr/bin/google-chrome-stable
  region: oregon
  buildCommand: apt-get update && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google-chrome.list && apt-get update && apt-get install -y google-chrome-stable && npm install
  startCommand: npm start
  autoDeployTrigger: commit