version: "1"
services:
- type: web
  name: general-notification
  runtime: docker
  repo: https://github.com/bad-boy-01/general-notification
  plan: free
  envVars:
  - key: DISCORD_WEBHOOK
    sync: false
  - key: PUPPETEER_CACHE_DIR
    value: /opt/render/.cache/puppeteer
  - key: PUPPETEER_EXECUTABLE_PATH
    value: /opt/render/.cache/puppeteer/chrome/linux-131.0.6778.204/chrome-linux64/chrome
  region: oregon
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit