version: "1"
services:
- type: web
  name: general-notification
  runtime: docker
  repo: https://github.com/bad-boy-01/general-notification
  plan: free
  envVars:
  - key: DISCORD_WEBHOOK
    sync: false
  - key: PUPPETEER_EXECUTABLE_PATH
    value: /usr/bin/google-chrome-stable
  region: oregon
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit