version: "1"
services:
- type: web
  name: general-notification
  runtime: docker
  repo: https://github.com/bad-boy-01/general-notification
  plan: free
  envVars:
  - key: DISCORD_WEBHOOK
    sync: false
  region: oregon
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit